name: electricity
description: "A new Flutter project."
publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  theme_tailor: ^3.0.2
  pinput: ^5.0.1
  gap: ^3.0.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
